sudo: false

language: c

env:
- PATH=~/racket/bin:$PATH

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- curl -L -o installer.sh http://plt.eecs.northwestern.edu/snapshots/current/installers/racket-test-current-x86_64-linux-precise.sh
- sh installer.sh --in-place --dest ~/racket/

install:
- curl -L -o master.zip https://github.com/takikawa/drracket-vim-tool/archive/master.zip
- unzip master.zip
- raco pkg install drracket-vim-tool/

script:
- racket -l drracket-vim-tool/tests/unit-tests
- echo "done"

after_script:
